# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strobe_level', models.IntegerField(choices=[(1, 'No Strobe'), (2, 'Low Strobe'), (3, 'Medium Strobe'), (4, 'High Strobe'), (5, 'Extreme Strobe')])),
                ('sound_level', models.IntegerField(choices=[(1, 'No Lound Sounds'), (2, 'Occasioanl Lound Sounds'), (3, 'Some Lound Sounds'), (4, 'Many Lound Sounds'), (5, 'Extremely Lound Sounds')])),
                ('rating', models.IntegerField(choices=[(1, 'No Problem'), (2, 'Little Problem'), (3, 'Medium Problem'), (4, 'Big Problem'), (5, 'Extreme Problem')])),
                ('review', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Movie')),
            ],
        ),
    ]
